.travis.yml, lib/autocomplete.js, lib/command.js, lib/program.js, lib/validator.js, package.json, tests/verbosity-quiet.js
Make Caporal compatible with node.js v4
=> Compat node v4

README.md
https://fishshell.com/docs/current/faq.html#faq-login-cmd
=> Fix fish's autorun file path

lib/program.js, tests/help.js, tests/issues/issue-13-negative-num-as-arg.js, tests/predefined-options.js
Force exiting for help command and -h, -V, --version options. Fixes #26
=> fix(program): Force exiting for help command and -h, -V, --version

lib/program.js, tests/help.js
Fix help command not exiting
Fixes #26
=> fix(help): Fix help command not exiting

README.md
Fixed optional argument schema.
=> README.md docs fix

lib/command.js, lib/program.js
An example, I've a file named `rebuild.js`:
```js
const Program = require( 'caporal/lib/program' );
const prog = new Program();
const initProg = () => prog
.version( '1.0.0' )
.description( 'Rebuild all feeds of a database' )
.option( '-d, --database', 'Database to use.', null, 'oadev', true )
.option( '-h, --host', 'Connect to host.', null, 'localhost', true )
.option( '-p, --port', 'Port number to use for connection.', prog.INT, 3306, true )
.option( '-u, --user', 'User for login.', null, 'root', true )
.option( '-p, --password', 'Password to use when connecting to server.', null, 'grut', true )
.action( ( args, options, logger ) => {
console.log( args, options );
logger.info( 'biiiip' );
return Promise.resolve( 'mabite' );
} );
initProg();
module.exports = ( ...args ) => prog.parse( [ …
```
=> feat(program,command): return promise of executed command for facilitate testing and reusing result of executed action

examples/pizza/pizza.js, lib/validator.js
=> fix(validator): fix handling of prog.LIST flag

README.md, examples/pizza/pizza.js, lib/command.js, lib/help.js, lib/program.js, tests/help.js, tests/predefined-options.js
Allow user to define a custom help for both global and commands (fixes
#30)
Also fixes #14.
=> feat(help): Added custom help feature

.gitignore, lib/autocomplete.js, tests/autocomplete.js
fix arguments autocompletion
Fixes #28
=> fix(autocomplete): fix arguments autocompletion

index.d.ts, package.json
=> feat: Add Typescript support

README.md
To apply the changes, you must run an additional command or restart the terminal
=> (docs) Update samples commands setup completion

lib/command.js, lib/program.js
I've added a "default-method", if no command is selected, the default command would be used.
=> feat(command) Default-Method

lib/help.js
=> fix(help): Display other commands when default command is present

README.md
See https://github.com/mattallty/Caporal.js/issues/78.
=> Fix Code sample for LIST parsing

lib/program.js
=> fix: exit with status code 1 when command does not exist

lib/command.js, tests/issues/issue-118-only-shortname-options.js
=> Fix error label when only short name option is provided

README.md, index.d.ts, lib/colorful.js, lib/command.js, lib/help.js, lib/option.js, package.json
=> A few fixes and improvements

README.md
Fix an error in the docs where the amount is not explicitly put.
Closes #132
=> Fix wrong doc specification for flags

examples/pizza/package.json, lib/autocomplete.js, lib/validator.js, tests/autocomplete.js
- Fixes autocompletion of arguments
- Fix validation error for LIST 
Should fix #136
=> Various fixes

lib/help.js
Property "bin" was ignored in the help "USAGE" section. Fixes #146
=> fix(help): Fix help usage output

lib/command.js, lib/validator.js, tests/option-validation.js
This pull request fixes an issue with options using custom validator functions where values in the
option object were set to undefined. This pull also includes new tests which check that options are
set correctly to prevent a regression in the future.
Closes #149
=> fix(validator): Fix function validators for options

src/command/__tests__/import.spec.ts, src/command/import.ts
Fix importCommand() to handle both typescript and javascript files
=> fix(command): Fix importCommand()

src/command/import.ts, src/command/scan.ts, src/help/templates/program.ts, src/index.ts, src/program/index.ts
Make webpack ignoring dynamic require
=> fix(command): Fix command discovery

docs/DEPENDENTS.md
In case you'd like to have this on the list; no worries if not!
=> Add glTF-Transform CLI to dependents list
