- README.md
Fixing regexp in example, as currently it won't run saying 
`Invalid value 'production' for argument env.`
> docs(README): Fix example RegExp

- lib/program.js
- tests/arg-validation.js
This yet throws a generic error, as we try to `toLowerCase` an undefined variable
> fix(autocomplete): Handle error when no argument is given to autocomplete helper

- lib/autocomplete.js
- lib/program.js
- package.json
- tests/arg-validation.js
- tests/autocomplete.js
- tests/issues/issue-13-negative-num-as-arg.js
- tests/option-validation.js
- yarn.lock
This fixes the way we parse process.argv and handle negative numbers. Negative numbers cannot be
used for options names from now on. Using micromist instead of minimist to resolve this problem.
Fixes #13.
> fix(parsing): Fixes negative numbers parsing as argument

- lib/command.js
Using --no-color was throwing "Error: Unknown option --color"
Fixes #19
> fix(options): Fix handling of --no-color option

- lib/logger.js
- tests/logger.js
Fix logger new line character after metadata 
Fixes #25
> fix(logger): Fix logger new line character after metadata

- lib/command.js
- tests/option-validation.js
Fix options parsing when only short name is defined. Fixes #29
> fix: Fix options parsing when only short name is defined

- lib/help.js
Use console.log for help() instead of custom logger. Fixes #34
> fix(help): use console.log for help() instead of custom logger

- lib/logger.js
- tests/logger.js
Fix logged string which was missing new line char when no metadata were provided
> fix(logger): Fix logger (new line missing)

- lib/logger.js
fix the way we handle metadata check in logger to prevent double LF
> fix(logger): fix logger metadata handling

- README.md
Added more detail and hence, hopefully clarity, to the logger examples. This should help people like myself who have never used winston, and had assumed from the way the docs were that logger.log and logger.info were the same as each other, which they're not.
> Clarified logger examples

- lib/command.js
Removed clumsy wording (probably from a previous change in wording) in error displayed when
.action() is missing.
> fix: make wording of error clearer

- README.md
I noticed a few copy/paste mistakes when reading the auto-completion section of the `README` 📝 
This pull request updates the comments to reflect code & vice versa. It also adds a missing comment for an option that returns a promise.
> Fix auto-completion README example

- lib/program.js
This will allow caporal to be `require`d from Node.js REPL. Useful when exploring the library's API.
Without this change, caporal would throw a `TypeError: Path must be a string. Received undefined` when requiring caporal from `node` REPL.
> Allow caporal to be used from REPL

- lib/argument.js
- lib/command.js
- lib/option.js
- lib/program.js
- lib/validator.js
I've noticed that PHPStorm ⚡️ is complaining about passing in an array as a validator for commands, arguments & options.
This pull request fixes the `validator` JSDoc type by adding `Array` to the allowed parameter types.
I've also fixed a typo in the validator class itself.
_P.S. Thanks for making such a great framework!_
> Fix validator JSDoc parameter type

- README.md
- lib/program.js
- package-lock.json
- package.json
- tests/exec.js
Hey @mattallty,
My company need this feature as we are mainly using Caporal for our long running process (aka workers).
While developing, we could use it programmatically against a some process manage (ie [pm2](https://github.com/Unitech/pm2)) that watch source files and reload on whatever changes.
This will save us some times and will allow us not to `^c` a running command and re-execute it manually. Especially if like us, you use Caporal in a docker container (yet we have to restart our docker-compose stack when we update our commands source).
Thanks,
Kinok
> Feat add execute method for programmatic usage

- index.d.ts
It seems you cant export expressions any more in exports in typescript 2.6.
I tested the prososed change successfully with these typescript versions:
* 2.6.1
* 2.4.2
> Fix typings for Typescript 2.6

- lib/help.js
Hi @mattallty 
I **really** love Caporal. It does pretty much everything, that I could have hoped for, except the one little thing mentioned in #85 
It does not really make any sense to display `this._program.bin()` if `this._program.name()` is available. I've made it so the presence of a `name` takes priority over `bin`
Applying this change, and running the `examples/pizza.js` changes it from
```
pizza.js 1.0.0
USAGE
pizza.js <command> [options]
```
to
```
pizzaparty 1.0.0
USAGE
pizzaparty <command> [options]
```
when modifying it to
```
prog
.name('pizzaparty')
.parse(process.argv);
```
@mattallty Any chance this could get merged asap and have version `0.10.0` (or `0.9.1` depending on your versioning strategy) released? We really need this to be available for the application we are …
> Make USAGE display name if available

- lib/command.js
- lib/error/invalid-argument-value.js
- lib/error/invalid-option-value.js
Hi @mattallty 
I also ran into the issue described in #94 so I decided to poke around and see what I could do. He suggested an alternative solution than the one I took. Mine
is based on a couple of assumptions
1. If we get to the point where [a fn validator for an argument](https://github.com/mattallty/Caporal.js/blob/master/lib/command.js#L249) fails, or to the point where [a fn validator for an option](https://github.com/mattallty/Caporal.js/blob/master/lib/command.js#L293) then it is safe to assume that there will be an inner exception on `e` (i.e `e.meta.originalError` will have been set)
2. You were already passing along the caught exception, for the validation of options, so we should be fine doing the same for argument validation, hence I added that to the constructor arguments of …
> fix: Display thrown error message when validation fails

- index.d.ts
The types were assuming that Caporal could be imported as
`import program from 'caporal'` but it can't, it has to be
imported as `import * as program from 'caporal'`
> Fix #91 typescript types

- README.md
As of today, npm already sets the option`--save` by default
> Update npm install line

- lib/autocomplete.js
- lib/command.js
- lib/option.js
- lib/program.js
- package-lock.json
- package.json
- tests/issues/issue-107-implicit-boolean-option.js
A option which doesn't take a value is called as an implicit boolean
option.
A typical implicit boolean option is defined like below:
```
program
.command('command', 'Command')
.option('-f, --flag', 'Flag')
...
```
The default value of any implicit boolean option is always `true` even
though a value other than `false` is explicitly specified as its
default value.
There is no meaning to specify arguments other than `synopsis` and
`description`.  Because:
* `validator`: The option has no value to be validate
* `defaultValue`: The default value is always `false`
* `required`: Setting it `true` always makes the option value `true`
This patch together with mattallty/micromist#2 can fix #107.
> feat: Implicit boolean option

- README.md
- examples/pizza/package.json
- examples/pizza/typescript.ts
- index.d.ts
Logger interface handle many input types that were not supported as per `printf` style & `object`.
Also added a basic ts example.
> fix($compile): Extended ts type for logger

- .npmignore
Fixes https://github.com/mattallty/Caporal.js/issues/113
As looks that is not really solved.
It also solves this retireJS errors:
https://github.com/twbs/bootstrap/issues/28236
https://github.com/twbs/bootstrap/issues/20184
https://github.com/jquery/jquery/issues/2432
> ci: add docs folders to npmignore

- lib/command.js
- lib/program.js
- lib/utils.js
- lib/validator.js
- tests/actions.js
- tests/arg-validation.js
- tests/option-validation.js
- tests/validator.js
Resolves #137 
Adding support for returning a promise from function based argument and option validators
I chose to continue to allow `validator.validate(?)` to be able to return non-promise results to reduce the external impact, both in the tests and actual usage, of this change. Doing so makes the internals a bit more complex since we have to check whether the result of several calls are promises or not, then take appropriate action. I'm not sure if going the other route, converting `validator.validate(?)` to always return a promise, would have been a breaking change for users but it would have certainly required modifying many of the existing tests.
> Promise based validation of arguments and options

- package-lock.json
- package.json
Updated lodash version to address security vulnerabilities.
Addresses #153 (unless you'd rather switch to using a caret)
> chore: Updated lodash version

- .gitignore
- lib/command.js
- lib/program.js
- tests/fatal-error.js
If the -v / --verbose flag is set and an unhandled error is thrown, the stacktract of that error
will be rendered.  Fixed some bugs related to some unhandled exceptions not being handled correctly.
Add .idea to .gitignore.
Fixes #166
> feat: Add ability to display stacktraces from unhandled exceptions

- package.json
Currently direct dependencies are pinned to specific patch versions,
as a result, projects that use this repository cannot respond to
transitive dependency updates, for example #210 updates lodash to
address CVE‑2020-8203, however other projects need to wait for Caporal
to do this and update after a new version has been published, and cannot be more proactive to address vulnerabilities in transitive dependencies.
Other projects have been working around this by adding overrides to their package files, e.g: https://github.com/Scrivito/scrivito_example_app_js/commit/9bd42031c54a7693fdd328dc42fa979a48f3c19d
Beyond this, it looks like releases have not been pushed out recently, I'm guessing this is due to incorrectly formatted commit messages? So people who use this library are still currently …
> fix: unpin dependencies
